# .goreleaser.yml
build:
  goos:
    - linux
  goarch:
    - amd64
  cgo: true
  env:
    - CGO_ENABLED=1
  flags:
    - -v
  ldflags:
    - -X main.version={{.Env.VERSION}}

release:
  github:
    owner: gigagrug
    name: idk
# You can add more configurations for custom file names, etc.

