# .goreleaser.yml
build:
  goos:
    - linux
  goarch:
    - amd64
  env:
    - CGO_ENABLED=1
  flags:
    - -v

release:
  github:
    owner: gigagrug
    name: idk
# You can add more configurations for custom file names, etc.

