name: Go Cross-Platform Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build ${{ matrix.goos }} ${{ matrix.goarch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Build binary
        run: |
          mkdir -p dist/
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/schema ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: schema-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/schema
