name: Build & Release Schema

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version (0.1.0)"
        required: true

jobs:
  build:
    name: ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go (1.24.3)
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 CGO_ENABLED=1 CC=gcc go build -ldflags "-X main.version=${{ inputs.version }}" -o dist/schema .
          echo "BINARY=dist/schema" >> $GITHUB_ENV

      - name: Create GitHub Release & Upload Binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ inputs.version }}
          files: ${{ env.BINARY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
