name: Build & Release Schema

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version (0.1.0)"
        required: true

jobs:
  build:
    name: ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux]
        goarch: [amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev

      - name: Build schema binary
        run: |
          if [ "${{ matrix.goos }}" == "linux" ]; then
            export CC=gcc
          elif [ "${{ matrix.goos }}" == "windows" ]; then
            export CC=x86_64-w64-mingw32-gcc
          fi
          echo "CC set to: $CC"
          mkdir -p dist
          ext=""
          if [ "${{ matrix.goos }}" == "windows" ]; then
            ext=".exe"
          fi
          output_name=schema-${{ matrix.goos }}-${{ matrix.goarch }}$ext
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=1 CC=$CC go build -ldflags "-X main.version=${{ inputs.version }}" -o dist/$output_name .
          echo "BINARY=dist/$output_name" >> $GITHUB_ENV

      - name: Create GitHub Release & Upload Binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ inputs.version }}
          files: ${{ env.BINARY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
