name: Build & Release Schema

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version (e.g. 0.1.0)"
        required: true

jobs:
  build:
    name: ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go (1.24.3)
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y build-essential

      # - name: Set version environment variable
      #   run: echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Build and Release with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
