name: Build & Release Schema

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # Adjust as needed

      - name: Build schema binary
        run: |
          mkdir -p dist
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then ext=".exe"; fi
          OUTPUT=dist/schema-${{ matrix.goos }}-${{ matrix.goarch }}$ext
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $OUTPUT .
          echo "BUILT_BINARY=$OUTPUT" >> $GITHUB_ENV

      - name: Upload artifact (for manual runs or inspection)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: schema-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ env.BUILT_BINARY }}

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          body: Body- Version number ${{inputs.version }}
          files: ${{ env.BUILT_BINARY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
