name: Build & Release Schema

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version (e.g. 0.1.0)"
        required: true

jobs:
  build:
    name: ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go (1.24.3)
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install GoReleaser
        run: |
          curl -sSL https://github.com/goreleaser/goreleaser/releases/download/v1.22.0/goreleaser_1.22.0_Linux_x86_64.tar.gz | tar -xzv
          sudo mv goreleaser /usr/local/bin/goreleaser

      - name: Build and Release with GoReleaser
        run: |
          VERSION=${{ inputs.version }} goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ inputs.version }}
