name: Build & Release Schema

on:
  workflow_dispatch: # Manual trigger via GitHub UI
  push:
    tags:
      - "v*" # Trigger when a version tag is pushed (e.g., v1.2.3)

jobs:
  build:
    name: Build schema for ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build schema binary
        run: |
          mkdir -p dist/${{ matrix.goos }}-${{ matrix.goarch }}
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then ext=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/${{ matrix.goos }}-${{ matrix.goarch }}/schema$ext .

      - name: Archive binary
        run: |
          cd dist/${{ matrix.goos }}-${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip ../schema-${{ matrix.goos }}-${{ matrix.goarch }}.zip schema.exe
          else
            tar -czf ../schema-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz schema
          fi

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/schema-${{ matrix.goos }}-${{ matrix.goarch }}.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
