name: Build & Release Schema

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version (0.1.0)"
        required: true

jobs:
  linux-build:
    name: Build Linux Binary (Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build using Docker
        run: |
          docker build -t schema-builder -f Dockerfile .
          docker create --name extract schema-builder
          docker cp extract:/usr/local/bin/schema-windows-amd64.exe ./dist/
          docker cp extract:/usr/local/bin/schema-linux-amd64 ./dist/
          docker rm extract

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: schema
          path: dist/*

  release:
    name: Create GitHub Release
    needs: linux-build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ inputs.version }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
